# Copyright 2024 The HuggingFace Inc. team. All rights reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""
Records a dataset. Actions for the robot can be either generated by teleoperation or by a policy.

Example:

```shell
lerobot-record \
    --robot.type=so100_follower \
    --robot.port=/dev/tty.usbmodem58760431541 \
    --robot.cameras="{laptop: {type: opencv, index_or_path: 0, width: 640, height: 480, fps: 30}}" \
    --robot.id=black \
    --dataset.repo_id=<my_username>/<my_dataset_name> \
    --dataset.num_episodes=2 \
    --dataset.single_task="Grab the cube" \
    --display_data=true
    # <- Optional: specify video codec (h264, hevc, libsvtav1). Default is libsvtav1. \
    # --dataset.vcodec=h264 \
    # <- Teleop optional if you want to teleoperate to record or in between episodes with a policy \
    # --teleop.type=so100_leader \
    # --teleop.port=/dev/tty.usbmodem58760431551 \
    # --teleop.id=blue \
    # <- Policy optional if you want to record with a policy \
    # --policy.path=${HF_USER}/my_policy \
```

Example recording with bimanual so100:
```shell
lerobot-record \
  --robot.type=bi_so_follower \
  --robot.left_arm_config.port=/dev/tty.usbmodem5A460822851 \
  --robot.right_arm_config.port=/dev/tty.usbmodem5A460814411 \
  --robot.id=bimanual_follower \
  --robot.left_arm_config.cameras='{
    wrist: {"type": "opencv", "index_or_path": 1, "width": 640, "height": 480, "fps": 30},
    top: {"type": "opencv", "index_or_path": 3, "width": 640, "height": 480, "fps": 30},
  }' --robot.right_arm_config.cameras='{
    wrist: {"type": "opencv", "index_or_path": 2, "width": 640, "height": 480, "fps": 30},
    front: {"type": "opencv", "index_or_path": 4, "width": 640, "height": 480, "fps": 30},
  }' \
  --teleop.type=bi_so_leader \
  --teleop.left_arm_config.port=/dev/tty.usbmodem5A460852721 \
  --teleop.right_arm_config.port=/dev/tty.usbmodem5A460819811 \
  --teleop.id=bimanual_leader \
  --display_data=true \
  --dataset.repo_id=${HF_USER}/bimanual-so-handover-cube \
  --dataset.num_episodes=25 \
  --dataset.single_task="Grab and handover the red cube to the other arm"
```
"""

import logging
import time
from dataclasses import asdict, dataclass, field
from pathlib import Path
from pprint import pformat
from typing import Any

from lerobot.cameras import (  # noqa: F401
    CameraConfig,  # noqa: F401
)
from lerobot.cameras.opencv.configuration_opencv import OpenCVCameraConfig  # noqa: F401
from lerobot.cameras.orbbec.configuration_orbbec import (  # noqa: F401
    OrbbecColorCameraConfig,
    OrbbecDepthCameraConfig,
)
from lerobot.cameras.reachy2_camera.configuration_reachy2_camera import Reachy2CameraConfig  # noqa: F401
from lerobot.cameras.realsense.configuration_rs_d405 import (  # noqa: F401
    RealSenseD405ColorCameraConfig,
    RealSenseD405DepthCameraConfig,
)
from lerobot.cameras.realsense.configuration_rs_d435i import (  # noqa: F401
    RealSenseD435iColorCameraConfig,
    RealSenseD435iDepthCameraConfig,
)
from lerobot.cameras.zmq.configuration_zmq import ZMQCameraConfig  # noqa: F401
from lerobot.configs import parser
from lerobot.configs.policies import PreTrainedConfig
from lerobot.datasets.image_writer import safe_stop_image_writer
from lerobot.datasets.lerobot_dataset import LeRobotDataset
from lerobot.datasets.pipeline_features import aggregate_pipeline_dataset_features, create_initial_features
from lerobot.datasets.utils import build_dataset_frame, combine_feature_dicts
from lerobot.datasets.video_utils import VideoEncodingManager
from lerobot.policies.factory import make_policy, make_pre_post_processors
from lerobot.policies.pretrained import PreTrainedPolicy
from lerobot.policies.utils import make_robot_action
from lerobot.processor import (
    PolicyAction,
    PolicyProcessorPipeline,
    RobotAction,
    RobotObservation,
    RobotProcessorPipeline,
    make_default_processors,
)
from lerobot.processor.rename_processor import rename_stats
from lerobot.robots import (  # noqa: F401
    Robot,
    RobotConfig,
    bi_openarm_follower,
    bi_so_follower,
    earthrover_mini_plus,
    hope_jr,
    koch_follower,
    make_robot_from_config,
    omx_follower,
    openarm_follower,
    reachy2,
    so_follower,
    unitree_g1 as unitree_g1_robot,
)
from lerobot.teleoperators import (  # noqa: F401
    Teleoperator,
    TeleoperatorConfig,
    bi_openarm_leader,
    bi_so_leader,
    homunculus,
    koch_leader,
    make_teleoperator_from_config,
    omx_leader,
    openarm_leader,
    reachy2_teleoperator,
    so_leader,
    unitree_g1,
)
from lerobot.teleoperators.keyboard.teleop_keyboard import KeyboardTeleop
from lerobot.utils.constants import ACTION, OBS_STR
from lerobot.utils.control_utils import (
    init_keyboard_listener,
    is_headless,
    predict_action,
    sanity_check_dataset_name,
    sanity_check_dataset_robot_compatibility,
)
from lerobot.utils.import_utils import register_third_party_plugins
from lerobot.utils.robot_utils import precise_sleep
from lerobot.utils.utils import (
    get_safe_torch_device,
    init_logging,
    log_say,
)
from lerobot.utils.visualization_utils import init_rerun, log_rerun_data


@dataclass
class DatasetRecordConfig:
    # Dataset identifier. By convention it should match '{hf_username}/{dataset_name}' (e.g. `lerobot/test`).
    repo_id: str
    # A short but accurate description of the task performed during the recording (e.g. "Pick the Lego block and drop it in the box on the right.")
    single_task: str
    # Root directory where the dataset will be stored (e.g. 'dataset/path').
    root: str | Path | None = None
    # Limit the frames per second.
    fps: int = 30
    # Number of seconds for data recording for each episode.
    episode_time_s: int | float = 60
    # Number of seconds for resetting the environment after each episode.
    reset_time_s: int | float = 60
    # Number of episodes to record.
    num_episodes: int = 50
    # Encode frames in the dataset into video
    video: bool = True
    # Upload dataset to Hugging Face hub.
    push_to_hub: bool = True
    # Upload on private repository on the Hugging Face hub.
    private: bool = False
    # Add tags to your dataset on the hub.
    tags: list[str] | None = None
    # Number of subprocesses handling the saving of frames as PNG. Set to 0 to use threads only;
    # set to ≥1 to use subprocesses, each using threads to write images. The best number of processes
    # and threads depends on your system. We recommend 4 threads per camera with 0 processes.
    # If fps is unstable, adjust the thread count. If still unstable, try using 1 or more subprocesses.
    num_image_writer_processes: int = 0
    # Number of threads writing the frames as png images on disk, per camera.
    # Too many threads might cause unstable teleoperation fps due to main thread being blocked.
    # Not enough threads might cause low camera fps.
    num_image_writer_threads_per_camera: int = 4
    # Number of episodes to record before batch encoding videos
    # Set to 1 for immediate encoding (default behavior), or higher for batched encoding
    video_encoding_batch_size: int = 1
    # Video codec for encoding videos. Options: 'h264', 'hevc', 'libsvtav1'.
    # Use 'h264' for faster encoding on systems where AV1 encoding is CPU-heavy.
    vcodec: str = "libsvtav1"
    # Rename map for the observation to override the image and state keys
    rename_map: dict[str, str] = field(default_factory=dict)

    def __post_init__(self):
        if self.single_task is None:
            raise ValueError("You need to provide a task as argument in `single_task`.")


@dataclass
class RecordConfig:
    robot: RobotConfig
    dataset: DatasetRecordConfig
    # Whether to control the robot with a teleoperator
    teleop: TeleoperatorConfig | None = None
    # Whether to control the robot with a policy
    policy: PreTrainedConfig | None = None
    # Display all cameras on screen
    display_data: bool = False
    # Display data on a remote Rerun server
    display_ip: str | None = None
    # Port of the remote Rerun server
    display_port: int | None = None
    # Whether to  display compressed images in Rerun
    display_compressed_images: bool = False
    # Use vocal synthesis to read events.
    play_sounds: bool = True
    # Resume recording on an existing dataset.
    resume: bool = False
    # Manually delimit episodes with Space, Q, and Escape.
    manual_episode_control: bool = False
    # B601 real-robot policy safety guard. When enabled, one gripper
    # close/open cycle completes the rollout and returns the arm to zero. A
    # stationary timeout is enforced only after the arm has left its startup
    # pose and before that close/open cycle completes.
    safety_single_grasp: bool = False
    safety_stationary_timeout_s: float = 5.0
    safety_motion_delta_deg: float = 0.5
    safety_start_delta_deg: float = 3.0
    safety_gripper_closed_deg: float = 80.0
    safety_gripper_open_deg: float = 20.0
    safety_zero_step_interval_s: float = 0.012
    safety_zero_velocity_scale: float = 1.30

    def __post_init__(self):
        # HACK: We parse again the cli args here to get the pretrained path if there was one.
        policy_path = parser.get_path_arg("policy")

        if policy_path:
            cli_overrides = parser.get_cli_overrides("policy")

            self.policy = PreTrainedConfig.from_pretrained(policy_path, cli_overrides=cli_overrides)
            self.policy.pretrained_path = policy_path

        if self.teleop is None and self.policy is None:
            raise ValueError("Choose a policy, a teleoperator or both to control the robot")
        if self.safety_stationary_timeout_s <= 0:
            raise ValueError("safety_stationary_timeout_s must be > 0")
        if self.safety_motion_delta_deg <= 0 or self.safety_start_delta_deg <= 0:
            raise ValueError("safety motion thresholds must be > 0")
        if self.safety_gripper_open_deg >= self.safety_gripper_closed_deg:
            raise ValueError("safety_gripper_open_deg must be less than safety_gripper_closed_deg")
        if self.safety_zero_step_interval_s < 0:
            raise ValueError("safety_zero_step_interval_s must be >= 0")
        if self.safety_zero_velocity_scale <= 0:
            raise ValueError("safety_zero_velocity_scale must be > 0")

    @classmethod
    def __get_path_fields__(cls) -> list[str]:
        """This enables the parser to load config from the policy using `--policy.path=local/dir`"""
        return ["policy"]


""" --------------- record_loop() data flow --------------------------
       [ Robot ]
           V
     [ robot.get_observation() ] ---> raw_obs
           V
     [ robot_observation_processor ] ---> processed_obs
           V
     .-----( ACTION LOGIC )------------------.
     V                                       V
     [ From Teleoperator ]                   [ From Policy ]
     |                                       |
     |  [teleop.get_action] -> raw_action    |   [predict_action]
     |          |                            |          |
     |          V                            |          V
     | [teleop_action_processor]             |          |
     |          |                            |          |
     '---> processed_teleop_action           '---> processed_policy_action
     |                                       |
     '-------------------------.-------------'
                               V
                  [ robot_action_processor ] --> robot_action_to_send
                               V
                    [ robot.send_action() ] -- (Robot Executes)
                               V
                    ( Save to Dataset )
                               V
                  ( Rerun Log / Loop Wait )
"""


class SingleGraspSafetyWatchdog:
    """Track one grasp cycle and detect a mid-rollout stationary arm.

    Position magnitudes are used for the gripper because B601 DM/RS variants
    use opposite signs in action space. Startup is excluded until an arm joint
    leaves its initial pose by ``start_delta_deg``. Completion is the first
    confirmed close followed by a confirmed reopen.
    """

    ARM_POSITION_KEYS = (
        "shoulder_pan.pos",
        "shoulder_lift.pos",
        "elbow_flex.pos",
        "wrist_flex.pos",
        "wrist_yaw.pos",
        "wrist_roll.pos",
    )

    def __init__(
        self,
        *,
        stationary_timeout_s: float,
        motion_delta_deg: float,
        start_delta_deg: float,
        gripper_closed_deg: float,
        gripper_open_deg: float,
    ) -> None:
        self.stationary_timeout_s = stationary_timeout_s
        self.motion_delta_deg = motion_delta_deg
        self.start_delta_deg = start_delta_deg
        self.gripper_closed_deg = gripper_closed_deg
        self.gripper_open_deg = gripper_open_deg
        self.initial_pose: tuple[float, ...] | None = None
        self.motion_anchor: tuple[float, ...] | None = None
        self.last_motion_time: float | None = None
        self.started = False
        self.gripper_closed_once = False
        self.ended = False

    def update(self, observation: RobotObservation, now: float) -> str | None:
        try:
            pose = tuple(float(observation[key]) for key in self.ARM_POSITION_KEYS)
            gripper_abs = abs(float(observation["gripper.pos"]))
        except (KeyError, TypeError, ValueError):
            return None

        if self.initial_pose is None:
            self.initial_pose = pose
            self.motion_anchor = pose
            return None

        if not self.started:
            if max(abs(a - b) for a, b in zip(pose, self.initial_pose, strict=True)) < self.start_delta_deg:
                return None
            self.started = True
            self.motion_anchor = pose
            self.last_motion_time = now

        if not self.gripper_closed_once and gripper_abs >= self.gripper_closed_deg:
            self.gripper_closed_once = True
            logging.info("Safety watchdog: first and only gripper close confirmed at %.1f deg", gripper_abs)
        elif self.gripper_closed_once and gripper_abs <= self.gripper_open_deg:
            if not self.ended:
                logging.info("Safety watchdog: gripper reopened; entering end phase")
            self.ended = True

        # The end pose is intentionally excluded from the stationary timeout.
        # A second close is rejected from the commanded action before it can be
        # sent to the robot (see ``check_action`` below).
        if self.ended:
            return None

        assert self.motion_anchor is not None
        assert self.last_motion_time is not None
        moved = max(abs(a - b) for a, b in zip(pose, self.motion_anchor, strict=True))
        if moved >= self.motion_delta_deg:
            self.motion_anchor = pose
            self.last_motion_time = now
        elif now - self.last_motion_time >= self.stationary_timeout_s:
            return "stationary_timeout"

        return None

    def check_action(self, action: RobotAction) -> str | None:
        """Reject a second gripper close before the command reaches hardware."""
        if not self.ended:
            return None
        try:
            gripper_target_abs = abs(float(action["gripper.pos"]))
        except (KeyError, TypeError, ValueError):
            return None
        if gripper_target_abs >= self.gripper_closed_deg:
            return "second_grasp_blocked"
        return None


def _run_policy_safety_return(
    robot: Robot,
    reason: str,
    step_interval_s: float,
    velocity_scale: float,
) -> None:
    logging.error("Policy safety return triggered: %s. Returning arm to zero.", reason)
    safe_zero = getattr(robot, "safe_zero", None)
    if not callable(safe_zero):
        raise RuntimeError("safety return requested but robot has no safe_zero() method")
    safe_zero(
        step_interval_s=step_interval_s,
        exit_on_complete=False,
        velocity_scale=velocity_scale,
    )
    logging.info("Policy safety return completed: %s", reason)


@safe_stop_image_writer
def record_loop(
    robot: Robot,
    events: dict,
    fps: int,
    teleop_action_processor: RobotProcessorPipeline[
        tuple[RobotAction, RobotObservation], RobotAction
    ],  # runs after teleop
    robot_action_processor: RobotProcessorPipeline[
        tuple[RobotAction, RobotObservation], RobotAction
    ],  # runs before robot
    robot_observation_processor: RobotProcessorPipeline[
        RobotObservation, RobotObservation
    ],  # runs after robot
    dataset: LeRobotDataset | None = None,
    teleop: Teleoperator | list[Teleoperator] | None = None,
    policy: PreTrainedPolicy | None = None,
    preprocessor: PolicyProcessorPipeline[dict[str, Any], dict[str, Any]] | None = None,
    postprocessor: PolicyProcessorPipeline[PolicyAction, PolicyAction] | None = None,
    control_time_s: int | None = None,
    single_task: str | None = None,
    display_data: bool = False,
    display_compressed_images: bool = False,
    visualization_status: str | None = None,
    safety_single_grasp: bool = False,
    safety_stationary_timeout_s: float = 5.0,
    safety_motion_delta_deg: float = 0.5,
    safety_start_delta_deg: float = 3.0,
    safety_gripper_closed_deg: float = 80.0,
    safety_gripper_open_deg: float = 20.0,
    safety_zero_step_interval_s: float = 0.012,
    safety_zero_velocity_scale: float = 1.30,
):
    if dataset is not None and dataset.fps != fps:
        raise ValueError(f"The dataset fps should be equal to requested fps ({dataset.fps} != {fps}).")

    teleop_arm = teleop_keyboard = None
    if isinstance(teleop, list):
        teleop_keyboard = next((t for t in teleop if isinstance(t, KeyboardTeleop)), None)
        teleop_arm = next(
            (
                t
                for t in teleop
                if isinstance(
                    t,
                    (
                        so_leader.SO100Leader
                        | so_leader.SO101Leader
                        | koch_leader.KochLeader
                        | omx_leader.OmxLeader
                    ),
                )
            ),
            None,
        )

        if not (teleop_arm and teleop_keyboard and len(teleop) == 2 and robot.name == "lekiwi_client"):
            raise ValueError(
                "For multi-teleop, the list must contain exactly one KeyboardTeleop and one arm teleoperator. Currently only supported for LeKiwi robot."
            )

    # Reset policy and processor if they are provided
    if policy is not None and preprocessor is not None and postprocessor is not None:
        policy.reset()
        preprocessor.reset()
        postprocessor.reset()

    safety_watchdog = None
    if safety_single_grasp and policy is not None:
        safety_watchdog = SingleGraspSafetyWatchdog(
            stationary_timeout_s=safety_stationary_timeout_s,
            motion_delta_deg=safety_motion_delta_deg,
            start_delta_deg=safety_start_delta_deg,
            gripper_closed_deg=safety_gripper_closed_deg,
            gripper_open_deg=safety_gripper_open_deg,
        )

    timestamp = 0
    start_episode_t = time.perf_counter()
    while timestamp < control_time_s:
        start_loop_t = time.perf_counter()

        if events["exit_early"]:
            events["exit_early"] = False
            break

        # Get robot observation
        obs = robot.get_observation()

        if safety_watchdog is not None:
            safety_reason = safety_watchdog.update(obs, time.monotonic())
            if safety_reason is not None:
                _run_policy_safety_return(
                    robot,
                    safety_reason,
                    safety_zero_step_interval_s,
                    safety_zero_velocity_scale,
                )
                events["stop_recording"] = True
                break

        # Applies a pipeline to the raw robot observation, default is IdentityProcessor
        obs_processed = robot_observation_processor(obs)

        if policy is not None or dataset is not None:
            observation_frame = build_dataset_frame(dataset.features, obs_processed, prefix=OBS_STR)

        # Get action from either policy or teleop
        if policy is not None and preprocessor is not None and postprocessor is not None:
            action_values = predict_action(
                observation=observation_frame,
                policy=policy,
                device=get_safe_torch_device(policy.config.device),
                preprocessor=preprocessor,
                postprocessor=postprocessor,
                use_amp=policy.config.use_amp,
                task=single_task,
                robot_type=robot.robot_type,
            )

            act_processed_policy: RobotAction = make_robot_action(action_values, dataset.features)

        elif policy is None and isinstance(teleop, Teleoperator):
            act = teleop.get_action()

            # Applies a pipeline to the raw teleop action, default is IdentityProcessor
            act_processed_teleop = teleop_action_processor((act, obs))

        elif policy is None and isinstance(teleop, list):
            arm_action = teleop_arm.get_action()
            arm_action = {f"arm_{k}": v for k, v in arm_action.items()}
            keyboard_action = teleop_keyboard.get_action()
            base_action = robot._from_keyboard_to_base_action(keyboard_action)
            act = {**arm_action, **base_action} if len(base_action) > 0 else arm_action
            act_processed_teleop = teleop_action_processor((act, obs))
        else:
            logging.info(
                "No policy or teleoperator provided, skipping action generation."
                "This is likely to happen when resetting the environment without a teleop device."
                "The robot won't be at its rest position at the start of the next episode."
            )
            continue

        # Applies a pipeline to the action, default is IdentityProcessor
        if policy is not None and act_processed_policy is not None:
            action_values = act_processed_policy
            robot_action_to_send = robot_action_processor((act_processed_policy, obs))
        else:
            action_values = act_processed_teleop
            robot_action_to_send = robot_action_processor((act_processed_teleop, obs))

        if safety_watchdog is not None:
            safety_reason = safety_watchdog.check_action(robot_action_to_send)
            if safety_reason is not None:
                _run_policy_safety_return(
                    robot,
                    safety_reason,
                    safety_zero_step_interval_s,
                    safety_zero_velocity_scale,
                )
                events["stop_recording"] = True
                break

        # Send action to robot
        # Action can eventually be clipped using `max_relative_target`,
        # so action actually sent is saved in the dataset. action = postprocessor.process(action)
        # TODO(steven, pepijn, adil): we should use a pipeline step to clip the action, so the sent action is the action that we input to the robot.
        _sent_action = robot.send_action(robot_action_to_send)
        # Save the command that the robot actually accepted after direction
        # mapping, safety limiting, and joint clipping. Some robots return
        # None, in which case keep the pre-existing behavior.
        action_to_record = _sent_action if _sent_action is not None else action_values

        # Write to dataset
        if dataset is not None:
            action_frame = build_dataset_frame(dataset.features, action_to_record, prefix=ACTION)
            frame = {**observation_frame, **action_frame, "task": single_task}
            dataset.add_frame(frame)

        if display_data:
            log_rerun_data(
                observation=obs_processed,
                action=action_to_record,
                compress_images=display_compressed_images,
                status_text=visualization_status,
            )

        dt_s = time.perf_counter() - start_loop_t
        precise_sleep(max(1 / fps - dt_s, 0.0))

        timestamp = time.perf_counter() - start_episode_t

    # A guarded rollout must never end by simply disabling torque at an
    # arbitrary airborne pose. Natural episode timeout and keyboard-driven
    # early exit use the same controlled zero return as the watchdog.
    if safety_watchdog is not None and not events["stop_recording"]:
        _run_policy_safety_return(
            robot,
            "episode_finished",
            safety_zero_step_interval_s,
            safety_zero_velocity_scale,
        )
        events["stop_recording"] = True


@parser.wrap()
def record(cfg: RecordConfig) -> LeRobotDataset:
    init_logging()
    logging.info(pformat(asdict(cfg)))
    if cfg.display_data:
        init_rerun(session_name="recording", ip=cfg.display_ip, port=cfg.display_port)
    display_compressed_images = (
        True
        if (cfg.display_data and cfg.display_ip is not None and cfg.display_port is not None)
        else cfg.display_compressed_images
    )

    robot = make_robot_from_config(cfg.robot)
    teleop = make_teleoperator_from_config(cfg.teleop) if cfg.teleop is not None else None

    teleop_action_processor, robot_action_processor, robot_observation_processor = make_default_processors()

    dataset_features = combine_feature_dicts(
        aggregate_pipeline_dataset_features(
            pipeline=teleop_action_processor,
            initial_features=create_initial_features(
                action=robot.action_features
            ),  # TODO(steven, pepijn): in future this should be come from teleop or policy
            use_videos=cfg.dataset.video,
        ),
        aggregate_pipeline_dataset_features(
            pipeline=robot_observation_processor,
            initial_features=create_initial_features(observation=robot.observation_features),
            use_videos=cfg.dataset.video,
        ),
    )

    dataset = None
    listener = None

    try:
        if cfg.resume:
            dataset = LeRobotDataset(
                cfg.dataset.repo_id,
                root=cfg.dataset.root,
                batch_encoding_size=cfg.dataset.video_encoding_batch_size,
                vcodec=cfg.dataset.vcodec,
            )

            if hasattr(robot, "cameras") and len(robot.cameras) > 0:
                dataset.start_image_writer(
                    num_processes=cfg.dataset.num_image_writer_processes,
                    num_threads=cfg.dataset.num_image_writer_threads_per_camera * len(robot.cameras),
                )
            sanity_check_dataset_robot_compatibility(dataset, robot, cfg.dataset.fps, dataset_features)
        else:
            # Create empty dataset or load existing saved episodes
            sanity_check_dataset_name(cfg.dataset.repo_id, cfg.policy)
            dataset = LeRobotDataset.create(
                cfg.dataset.repo_id,
                cfg.dataset.fps,
                root=cfg.dataset.root,
                robot_type=robot.name,
                features=dataset_features,
                use_videos=cfg.dataset.video,
                image_writer_processes=cfg.dataset.num_image_writer_processes,
                image_writer_threads=cfg.dataset.num_image_writer_threads_per_camera * len(robot.cameras),
                batch_encoding_size=cfg.dataset.video_encoding_batch_size,
                vcodec=cfg.dataset.vcodec,
            )

        # Load pretrained policy
        policy = None if cfg.policy is None else make_policy(cfg.policy, ds_meta=dataset.meta)
        preprocessor = None
        postprocessor = None
        if cfg.policy is not None:
            preprocessor, postprocessor = make_pre_post_processors(
                policy_cfg=cfg.policy,
                pretrained_path=cfg.policy.pretrained_path,
                dataset_stats=rename_stats(dataset.meta.stats, cfg.dataset.rename_map),
                preprocessor_overrides={
                    "device_processor": {"device": cfg.policy.device},
                    "rename_observations_processor": {"rename_map": cfg.dataset.rename_map},
                },
            )

        robot.connect()
        if teleop is not None:
            teleop.connect()

        listener, events = init_keyboard_listener()

        with VideoEncodingManager(dataset):
            if cfg.manual_episode_control:
                pending_episode = False
                recorded_episodes = dataset.num_episodes
                preview_status = "READY - PRESS SPACE TO START"

                while not events["stop_recording"]:
                    events["is_recording"] = False
                    log_say(
                        f"Preview ready ({recorded_episodes}/{cfg.dataset.num_episodes} saved). "
                        "Press Space to start, Q to delete the latest completed episode, or Escape to exit.",
                        cfg.play_sounds,
                    )
                    record_loop(
                        robot=robot,
                        events=events,
                        fps=cfg.dataset.fps,
                        teleop_action_processor=teleop_action_processor,
                        robot_action_processor=robot_action_processor,
                        robot_observation_processor=robot_observation_processor,
                        teleop=teleop,
                        policy=policy,
                        preprocessor=preprocessor,
                        postprocessor=postprocessor,
                        dataset=None,
                        control_time_s=float("inf"),
                        single_task=cfg.dataset.single_task,
                        display_data=cfg.display_data,
                        display_compressed_images=display_compressed_images,
                        visualization_status=preview_status,
                        safety_single_grasp=cfg.safety_single_grasp,
                        safety_stationary_timeout_s=cfg.safety_stationary_timeout_s,
                        safety_motion_delta_deg=cfg.safety_motion_delta_deg,
                        safety_start_delta_deg=cfg.safety_start_delta_deg,
                        safety_gripper_closed_deg=cfg.safety_gripper_closed_deg,
                        safety_gripper_open_deg=cfg.safety_gripper_open_deg,
                        safety_zero_step_interval_s=cfg.safety_zero_step_interval_s,
                        safety_zero_velocity_scale=cfg.safety_zero_velocity_scale,
                    )

                    if events["stop_recording"]:
                        break

                    if events["delete_last_episode"]:
                        events["delete_last_episode"] = False
                        if pending_episode:
                            dataset.clear_episode_buffer()
                            pending_episode = False
                            preview_status = "READY - PRESS SPACE TO START"
                            log_say("Latest completed episode deleted.", cfg.play_sounds)
                        else:
                            log_say("No unconfirmed episode to delete.", cfg.play_sounds)
                        continue

                    if not events["toggle_recording"]:
                        continue
                    events["toggle_recording"] = False

                    if pending_episode:
                        events["input_locked"] = True
                        try:
                            dataset.save_episode()
                        finally:
                            events["input_locked"] = False
                        recorded_episodes += 1
                        pending_episode = False

                    if recorded_episodes >= cfg.dataset.num_episodes:
                        log_say(
                            f"Target of {cfg.dataset.num_episodes} episodes reached. Press Escape to finish.",
                            cfg.play_sounds,
                        )
                        continue

                    events["is_recording"] = True
                    log_say(
                        f"Recording episode {recorded_episodes}. Press Space to finish it.",
                        cfg.play_sounds,
                    )
                    record_loop(
                        robot=robot,
                        events=events,
                        fps=cfg.dataset.fps,
                        teleop_action_processor=teleop_action_processor,
                        robot_action_processor=robot_action_processor,
                        robot_observation_processor=robot_observation_processor,
                        teleop=teleop,
                        policy=policy,
                        preprocessor=preprocessor,
                        postprocessor=postprocessor,
                        dataset=dataset,
                        control_time_s=float("inf"),
                        single_task=cfg.dataset.single_task,
                        display_data=cfg.display_data,
                        display_compressed_images=display_compressed_images,
                        visualization_status="RECORDING - PRESS SPACE TO FINISH",
                        safety_single_grasp=cfg.safety_single_grasp,
                        safety_stationary_timeout_s=cfg.safety_stationary_timeout_s,
                        safety_motion_delta_deg=cfg.safety_motion_delta_deg,
                        safety_start_delta_deg=cfg.safety_start_delta_deg,
                        safety_gripper_closed_deg=cfg.safety_gripper_closed_deg,
                        safety_gripper_open_deg=cfg.safety_gripper_open_deg,
                        safety_zero_step_interval_s=cfg.safety_zero_step_interval_s,
                        safety_zero_velocity_scale=cfg.safety_zero_velocity_scale,
                    )
                    events["is_recording"] = False

                    if events["stop_recording"]:
                        dataset.clear_episode_buffer()
                        log_say("Active incomplete episode discarded.", cfg.play_sounds)
                        break

                    if events["toggle_recording"]:
                        events["toggle_recording"] = False
                        pending_episode = dataset.episode_buffer["size"] > 0
                        if pending_episode:
                            preview_status = "FINISHED - SPACE: SAVE NEXT  Q: DELETE"
                            log_say(
                                "Episode completed. Press Q to delete it, Space to confirm it and start the next, "
                                "or Escape to save it and exit.",
                                cfg.play_sounds,
                            )

                if pending_episode:
                    events["input_locked"] = True
                    try:
                        dataset.save_episode()
                    finally:
                        events["input_locked"] = False
                return dataset

            recorded_episodes = 0
            while recorded_episodes < cfg.dataset.num_episodes and not events["stop_recording"]:
                log_say(f"Recording episode {dataset.num_episodes}", cfg.play_sounds)
                record_loop(
                    robot=robot,
                    events=events,
                    fps=cfg.dataset.fps,
                    teleop_action_processor=teleop_action_processor,
                    robot_action_processor=robot_action_processor,
                    robot_observation_processor=robot_observation_processor,
                    teleop=teleop,
                    policy=policy,
                    preprocessor=preprocessor,
                    postprocessor=postprocessor,
                    dataset=dataset,
                    control_time_s=cfg.dataset.episode_time_s,
                    single_task=cfg.dataset.single_task,
                    display_data=cfg.display_data,
                    display_compressed_images=display_compressed_images,
                    safety_single_grasp=cfg.safety_single_grasp,
                    safety_stationary_timeout_s=cfg.safety_stationary_timeout_s,
                    safety_motion_delta_deg=cfg.safety_motion_delta_deg,
                    safety_start_delta_deg=cfg.safety_start_delta_deg,
                    safety_gripper_closed_deg=cfg.safety_gripper_closed_deg,
                    safety_gripper_open_deg=cfg.safety_gripper_open_deg,
                    safety_zero_step_interval_s=cfg.safety_zero_step_interval_s,
                    safety_zero_velocity_scale=cfg.safety_zero_velocity_scale,
                )

                # Execute a few seconds without recording to give time to manually reset the environment
                # Skip reset for the last episode to be recorded
                if not events["stop_recording"] and (
                    (recorded_episodes < cfg.dataset.num_episodes - 1) or events["rerecord_episode"]
                ):
                    log_say("Reset the environment", cfg.play_sounds)

                    # reset g1 robot
                    if robot.name == "unitree_g1":
                        robot.reset()

                    record_loop(
                        robot=robot,
                        events=events,
                        fps=cfg.dataset.fps,
                        teleop_action_processor=teleop_action_processor,
                        robot_action_processor=robot_action_processor,
                        robot_observation_processor=robot_observation_processor,
                        teleop=teleop,
                        control_time_s=cfg.dataset.reset_time_s,
                        single_task=cfg.dataset.single_task,
                        display_data=cfg.display_data,
                    )

                if events["rerecord_episode"]:
                    log_say("Re-record episode", cfg.play_sounds)
                    events["rerecord_episode"] = False
                    events["exit_early"] = False
                    dataset.clear_episode_buffer()
                    continue

                dataset.save_episode()
                recorded_episodes += 1
    finally:
        log_say("Stop recording", cfg.play_sounds, blocking=True)

        if dataset:
            dataset.finalize()

        if robot.is_connected:
            robot.disconnect()
        if teleop and teleop.is_connected:
            teleop.disconnect()

        if not is_headless() and listener:
            listener.stop()

        if cfg.dataset.push_to_hub:
            dataset.push_to_hub(tags=cfg.dataset.tags, private=cfg.dataset.private)

        log_say("Exiting", cfg.play_sounds)
    return dataset


def main():
    register_third_party_plugins()
    record()


if __name__ == "__main__":
    main()
